version: "3"
services:
  php:
    environment:
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_MAX_EXECUTION_TIME: 2048
      PHP_MEMORY_LIMIT: 1024
    volumes:
      - ./:/var/www/html
  apache:
    volumes:
      - ./:/var/www/html
  mailhog:
    ports:
      - 1025:1025
      - 8025:8025
